config/routes.rb
Rails.application.routes.draw do
  resources :page_monitors do
    post 'preview', on: :new
  end

  root to: 'page_monitors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page_monitor.rb
class PageMonitor < ApplicationRecord
  after_create :request_update

  validates :url, presence: true
  validates :name, presence: true
  validates :frequency, presence: true,
    numericality: { only_integer: true, greater_than_or_equal_to: 600 }
  validate :validate_url_reachable

  def request_update
    UpdatePageMonitorJob.perform_later(self)
  end

private

  def validate_url_reachable
    HTTParty.get(url)
  rescue StandardError
    errors.add(:url, 'unable to connect')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_monitors_controller.rb
class PageMonitorsController < ApplicationController
  before_action :set_page_monitor, only: [:show, :edit, :update, :destroy]

  # GET /page_monitors
  def index
    @page_monitors = PageMonitor.all
  end

  # GET /page_monitors/1
  def show
  end

  # GET /page_monitors/new
  def new
    @page_monitor = PageMonitor.new
  end

  # GET /page_monitors/1/edit
  def edit
  end

  # POST /page_monitors
  def create
    @page_monitor = PageMonitor.new(permitted_params)

    respond_to do |format|
      if @page_monitor.save
        format.html { redirect_to @page_monitor, notice: 'PageMonitor was successfully created.' }
        format.json { render :show, status: :created, location: @page_monitor }
      else
        format.html { render :new }
        format.json { render json: @page_monitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_monitors/1
  def update
    respond_to do |format|
      if @page_monitor.update(permitted_params)
        format.html { redirect_to @page_monitor, notice: 'PageMonitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @page_monitor }
      else
        format.html { render :edit }
        format.json { render json: @page_monitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_monitors/1
  def destroy
    @page_monitor.destroy
    respond_to do |format|
      format.html { redirect_to page_monitors_url, notice: 'PageMonitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
    @preview = Observe::Scraper.call(permitted_params)
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_page_monitor
    @page_monitor = PageMonitor.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def permitted_params
    params.require(:page_monitor).permit(:url, :name, :enabled, :frequency, selections: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timespan_helper.rb
module TimespanHelper
  TIMESPAN_PERIODS = {
    'day' => 86_400,
    'hour' => 3_600,
    'minute' => 60
  }.freeze

  def humanize_seconds(seconds)
    seconds = seconds.to_i if seconds.is_a?(ActiveSupport::Duration)

    return 'now' if seconds.zero?

    results = TIMESPAN_PERIODS.map do |name, span|
      next if span > seconds

      amount, seconds = seconds.divmod(span)
      pluralize(amount, name)
    end
    results.compact.to_sentence
  end
end

app/views/home/index.html.erb
<h1>Hello World</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Observant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flex items-center justify-center px-4 pt-6 md:px-6 md:pt-12">
      <%= yield %>
    </div>
  </body>
</html>

app/views/page_monitors/_form.html.erb
<%= form_with(model: page_monitor, local: true, class: 'w-full', data: { controller: 'preview', 'preview-url': preview_new_page_monitor_path }) do |form| %>
  <% if page_monitor.errors.any? %>
    <div id="error_explanation" class="w-full">
      <h2><%= pluralize(page_monitor.errors.count, "error") %> prohibited this page_monitor from being saved:</h2>

      <ul>
        <% page_monitor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col w-full actions">
    <div class="flex flex-col mb-4">
      <%= form.label :url %>
      <%= form.text_field :url, class: 'w-full form-input', data: { target: 'preview.input' } %>
    </div>
    <div class="flex flex-col mb-4">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'w-full form-input' %>
    </div>
    <div class="flex flex-col mb-4">
      <%= form.label :enabled %>
      <%= form.check_box :enabled, class: 'form-checkbox' %>
    </div>
    <!--
    <div class="flex flex-col mb-4">
      <%= form.label :frequency %>
      <%= form.range_field :frequency, in: 600..86400, class: 'w-full h-3 transition-opacity bg-gray-300 outline-none opacity-75 appearance-none hover:opacity-100 slider' %>
    </div>
    -->
    <div class="flex flex-col mb-4">
      <%= form.label :frequency %>
      <%= form.number_field :frequency, class: 'w-full form-input', min: 600, step: 60 %>
    </div>
    <div class="flex flex-col mb-4" data-controller="array-input">
      <%= form.label :selections %>
      <div data-target="array-input.container">
        <% Array(page_monitor.selections).each do |selection| %>
          <div class="flex items-center mb-2" data-target="array-input.input">
            <input type="text" class="flex-1 form-textarea" value="<%= selection %>" name="page_monitor[selections][]" data-action="array-input#set" data-target="preview.input">
            <button class="flex-none w-6 h-6 ml-2 text-red-700 hover:text-red-800" data-action="array-input#remove">
              <svg class="w-full h-full" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM7 9a1 1 0 000 2h6a1 1 0 100-2H7z" clip-rule="evenodd"></path></svg>
            </button>
          </div>
        <% end %>
      </div>
      <template class="hidden" data-target="array-input.template">
        <div class="flex items-center mb-2" data-target="array-input.input">
          <input type="text" disabled="disabled" class="flex-1 form-textarea" value="" name="page_monitor[selections][]" data-action="array-input#set" data-target="preview.input">
          <button class="flex-none w-6 h-6 ml-2 text-red-700 hover:text-red-800" data-action="array-input#remove">
            <svg class="w-full h-full" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM7 9a1 1 0 000 2h6a1 1 0 100-2H7z" clip-rule="evenodd"></path></svg>
          </button>
        </div>
      </template>
      <div class="flex justify-end">
        <button class="flex-none w-6 h-6 ml-2 text-green-700 hover:text-green-800" data-action="array-input#add">
          <svg class="w-full h-full" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v2H7a1 1 0 100 2h2v2a1 1 0 102 0v-2h2a1 1 0 100-2h-2V7z" clip-rule="evenodd"></path></svg>
        </button>
      </div>
    </div>
    <div class="mb-4">
      <%= form.submit 'Update', class: 'px-6 py-2 text-white bg-blue-700 rounded-sm cursor-pointer' %>
      <button class="px-6 py-2 text-white bg-blue-700 rounded-sm" data-action="preview#get">Preview</button>
    </div>
  </div>
<% end %>

app/views/page_monitors/edit.html.erb
<p id="notice"><%= notice %></p>

<div class="flex flex-col w-full max-w-screen-xl">
  <div class="flex items-center flex-none h-16">
    <div class="flex items-center flex-1 text-gray-700">
      <%= link_to page_monitors_path, class: 'hover:text-blue-700' do %>
        <svg class="inline-block w-8 h-8" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
      <% end %>
      <h1 class="inline-block text-2xl font-semibold">
        Editing Page Monitor
      </h1>
    </div>
    <div class="flex justify-end flex-none w-48">
      <%= link_to @page_monitor, class: 'flex items-center justify-center w-full h-10 text-white bg-blue-600 rounded-sm hover:bg-blue-700' do %>
        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20"><path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path><path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd"></path></svg>
        <div class="ml-2">Show</div>
      <% end %>
    </div>
  </div>
  <div class="flex-1">
    <%= render 'form', page_monitor: @page_monitor %>
  </div>
</div>

app/views/page_monitors/index.html.erb
<p id="notice"><%= notice %></p>

<div class="flex flex-col w-full max-w-screen-xl">
  <div class="flex items-center flex-none h-16">
    <div class="flex-1 text-gray-700">
      <h1 class="text-2xl font-semibold">Page Monitors</h1>
    </div>
    <div class="flex justify-end flex-none w-48">
      <%= link_to 'Add', new_page_monitor_path, class: 'flex items-center justify-center w-full h-10 text-white bg-green-700 rounded-sm hover:bg-green-800' %>
    </div>
  </div>
  <div class="flex-1 overflow-x-auto">
    <table class="w-full border-2 border-collapse border-gray-500">
      <thead>
        <tr>
          <th class="px-4 py-2 border border-gray-400">Name</th>
          <th class="px-4 py-2 border border-gray-400">Latest Content</th>
          <th class="px-4 py-2 border border-gray-400">Frequency</th>
          <th class="px-4 py-2 border border-gray-400">Last Check</th>
          <th class="px-4 py-2 border border-gray-400">Status</th>
          <th class="px-4 py-2 border border-gray-400" colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody class="text-sm">
        <% @page_monitors.each do |page_monitor| %>
          <tr>
            <td class="max-w-xs px-4 py-2 whitespace-no-wrap border border-gray-400">
              <div class="overflow-hidden">
                <%= link_to page_monitor.url, class: 'flex items-center text-blue-800 hover:text-blue-900 hover:underline', target: '_blank' do %>
                  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20"><path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"></path><path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"></path></svg>
                  <span><%= page_monitor.name %></span>
                <% end %>
              </div>
            </td>
            <td class="max-w-sm px-4 py-2 whitespace-no-wrap border border-gray-400">
              <div class="overflow-hidden">
                <%= page_monitor.content %>
              </div>
            </td>
            <td class="px-4 py-2 overflow-hidden text-center whitespace-no-wrap border border-gray-400">
              <%= humanize_seconds(page_monitor.frequency) %>
            </td>
            <td class="px-4 py-2 overflow-hidden text-center whitespace-no-wrap border border-gray-400">
              <%= time_ago_in_words(page_monitor.last_checked_at) %> ago
            </td>
            <td class="px-4 py-2 overflow-hidden text-center whitespace-no-wrap border border-gray-400">
              <%= page_monitor.enabled ? 'Enabled' : 'Disabled' %>
            </td>
            <td class="bg-blue-100 border border-gray-400">
              <%= link_to page_monitor, class: 'flex items-center justify-center w-full h-full px-4 py-2' do %>
                <svg class="w-6 h-6 text-blue-700" fill="currentColor" viewBox="0 0 20 20"><path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path><path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd"></path></svg>
              <% end %>
            </td>
            <td class="bg-yellow-100 border border-gray-400">
              <%= link_to edit_page_monitor_path(page_monitor), class: 'flex items-center justify-center w-full h-full px-4 py-2' do %>
                <svg class="w-6 h-6 text-yellow-700" fill="currentColor" viewBox="0 0 20 20"><path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path><path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"></path></svg>
              <% end %>
            </td>
            <td class="bg-red-100 border border-gray-400">
              <%= link_to page_monitor, class: 'flex items-center justify-center w-full h-full px-4 py-2', method: :delete, data: { confirm: 'Are you sure?' } do %>
                <svg class="w-6 h-6 text-red-700" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path></svg>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/page_monitors/new.html.erb
<p id="notice"><%= notice %></p>

<div class="flex flex-col w-full max-w-screen-xl">
  <div class="flex items-center flex-none h-16">
    <div class="flex items-center flex-1 text-gray-700">
      <%= link_to page_monitors_path, class: 'hover:text-blue-700' do %>
        <svg class="inline-block w-8 h-8" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
      <% end %>
      <h1 class="inline-block text-2xl font-semibold">
        New Page Monitor
      </h1>
    </div>
  </div>
  <div class="flex-1">
    <%= render 'form', page_monitor: @page_monitor %>
  </div>
</div>

app/views/page_monitors/preview.html.erb
<% simple_format(@preview) %>

app/views/page_monitors/show.html.erb
<p id="notice"><%= notice %></p>

<div class="flex flex-col w-full max-w-screen-xl">
  <div class="flex items-center flex-none h-16">
    <div class="flex items-center flex-1 text-gray-700">
      <%= link_to page_monitors_path, class: 'hover:text-blue-700' do %>
        <svg class="inline-block w-8 h-8" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
      <% end %>
      <h1 class="inline-block text-2xl font-semibold">
        <%= @page_monitor.name %>
      </h1>
    </div>
    <div class="flex justify-end flex-none w-48">
      <%= link_to edit_page_monitor_path(@page_monitor), class: 'flex items-center justify-center w-full h-10 text-white bg-yellow-600 rounded-sm hover:bg-yellow-700' do %>
        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20"><path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path><path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"></path></svg>
        <div class="ml-2">Edit</div>
      <% end %>
    </div>
  </div>
  <div class="flex-1">
    <table class="w-full">
      <tr class="align-top">
        <th class="px-4 py-2 text-left whitespace-no-wrap">Source</th>
        <td class="w-full px-4 py-2">
          <%= link_to @page_monitor.url, class: 'flex items-center text-blue-800 hover:text-blue-900 hover:underline', target: '_blank' do %>
            <span><%= @page_monitor.url %></span>
            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20"><path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"></path><path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"></path></svg>
          <% end %>
        </td>
      </tr>
      <tr class="align-top">
        <th class="px-4 py-2 text-left whitespace-no-wrap">Name</th>
        <td class="w-full px-4 py-2"><%= @page_monitor.name %></td>
      </tr>
      <tr class="align-top">
        <th class="px-4 py-2 text-left whitespace-no-wrap">Frequency</th>
        <td class="w-full px-4 py-2"><%= humanize_seconds(@page_monitor.frequency) %></td>
      </tr>
      <tr class="align-top">
        <th class="px-4 py-2 text-left whitespace-no-wrap">Status</th>
        <td class="w-full px-4 py-2">Enabled</td>
      </tr>
      <tr class="align-top">
        <th class="px-4 py-2 text-left whitespace-no-wrap">Last Check</th>
        <td class="w-full px-4 py-2"><%= time_ago_in_words(@page_monitor.last_checked_at) %></td>
      </tr>
      <tr class="align-top">
        <th class="px-4 py-2 text-left whitespace-no-wrap">Latest Content</th>
        <td class="w-full px-4 py-2"><%= simple_format(@page_monitor.content) %></td>
      </tr>
      <tr class="align-top">
        <th class="px-4 py-2 text-left whitespace-no-wrap">Previous Content</th>
        <td class="w-full px-4 py-2"><%= simple_format(@page_monitor.previous_content) %></td>
      </tr>
    </table>
  </div>
</div>